import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "./sidebar";
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "@/prismicio";
import Nav from "./components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "7eventy7",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Logo className="logo-container original" />
        <div className="main-layout">
          <Nav></Nav>
          <div className="details">{children}</div>
        </div>
        <Logo className="logo-container mirrored" />

        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  );
}
